_base_: "configs/pspnet/pspnet_resnet50_os8_cityscapes_1024x512_80k.yml"


batch_size: 4
iters: 10000


train_dataset:
  dataset_root: E:\Dev\GrapeSAM\Qunatifying-Grapevine-Cluster-Closure\Images\
  train_path: E:\Dev\GrapeSAM\Qunatifying-Grapevine-Cluster-Closure\Images\train.txt
  type: Dataset
  num_classes: 2
  mode: train
  transforms:
    - type: Resize
      target_size: [512, 512]
    - type: RandomHorizontalFlip
    - type: RandomVerticalFlip
    - type: Normalize


val_dataset:
  type: Dataset
  dataset_root: E:\Dev\GrapeSAM\Qunatifying-Grapevine-Cluster-Closure\Images\
  val_path: E:\Dev\GrapeSAM\Qunatifying-Grapevine-Cluster-Closure\Images\val.txt
  num_classes: 2
  mode: val
  transforms:
    - type: Resize
      target_size: [512, 512]
    - type: Normalize
